name: rp2 port

on:
  push:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - 'tools/**'
      - 'py/**'
      - 'extmod/**'
      - 'shared/**'
      - 'lib/**'
      - 'drivers/**'
      - 'ports/rp2/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install packages
      run: source tools/ci.sh && ci_rp2_setup
    - name: Build
      run: source tools/ci.sh && ci_rp2_build
    - name: find . | grep uf2
    - name: Copy result out of nix store
      run: cp src/build/.uf2 ./micropython.uf2
    - name: Upload result
      uses: actions/upload-artifact@v3
      with:
        name: micropython.uf2
        path: micropython.uf2

    #- name: Put environment variable into the env context
    #  run: echo "app_name=$APP_NAME" >> $GITHUB_ENV
    #- name: Push to release
    #  uses: softprops/action-gh-release@v1
    #  if: startsWith(github.ref, 'refs/tags/')
    #  with:
    #      files: ${{ env.app_name }}.uf2
    #      body_path: CHANGELOG.md
